name: voice_notes
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  record: ^5.0.4
  permission_handler: ^11.0.1
  path_provider: ^2.1.2
  just_audio: ^0.9.36
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_feather_icons: ^2.0.0+1
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/dubai/
    - assets/images/

  fonts:
    - family: dubai
      fonts:
        - asset: assets/fonts/dubai/Dubai-Regular.ttf
          weight: 400
        - asset: assets/fonts/dubai/Dubai-Medium.ttf
          weight: 500
        - asset: assets/fonts/dubai/Dubai-Bold.otf
          weight: 700